# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  sakura-plymouth =
    { stdenv }:
    stdenv.mkDerivation {
      pname = "sakura-plymouth";
      version = "1.0.0";
      src = ./plymouth;

      sourceRoot = ".";

      installPhase = ''
        mkdir -pv $out/share/plymouth/themes
        mv plymouth $out/share/plymouth/themes/sakura
        find $out/share/plymouth/themes/ -name \*.plymouth -exec sed -i "s@\/usr\/@$out\/@" {} \;
      '';
    };
in

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usbhid"
      "uas"
      "sd_mod"
    ];
    kernelParams = [
      "quiet"
      "udev.log_level=3"
      "systemd.show_status=auto"
    ];
    kernelModules = [
      "mt7921e"
      "coretemp"
      "cpuid"
      "v4l2loopback"
    ];
    extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];

    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 0;
    };

    # Use latest kernel.
    kernelPackages = pkgs.linuxPackages_latest;

    extraModprobeConfig = ''
      options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    '';

    plymouth = {
      enable = true;
      theme = "sakura";
      themePackages = with pkgs; [
        (adi1090x-plymouth-themes.override {
          selected_themes = [ "pixels" ];
        })
        (callPackage sakura-plymouth { })
      ];
    };
    consoleLogLevel = 3;
    initrd = {
      verbose = false;
      kernelModules = [ "amdgpu" ];
    };
  };
  systemd.services."display-manager" = {
    conflicts = [ "plymouth-quit.service" ];
    preStart = "${pkgs.plymouth}/bin/plymouth deactivate";
    postStart = "/bin/sh -c 'sleep 5 && ${pkgs.plymouth}/bin/plymouth quit --retain-splash'";
    enable = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/522bf312-3eb8-46c0-b5b5-495c4d48cff6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/766C-3FAF";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/2d9e9125-e38e-4704-aa7e-4f876c6d88e1"; }
  ];
  networking = {
    useDHCP = lib.mkDefault true;
    interfaces.enp6s0.useDHCP = lib.mkDefault true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
