{
  imports = [
    ./lsp
    ./aerial.nix
    ./autopairs.nix
    ./blink.nix
    ./bufferline.nix
    ./gitsigns.nix
    ./hlchunk.nix
    ./lazygit.nix
    ./lualine.nix
    ./direnv.nix
    ./nix-develop.nix
    ./noice.nix
    ./neoscroll.nix
    ./notify.nix
    ./rustaceanvim.nix
    ./smear-cursor.nix
    ./snacks.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./treesj.nix
    ./ts-comments.nix
    ./whichkey.nix
    ./yanky.nix
    ./mini.nix
    ./todo-comments.nix
    ./flash.nix
  ];
}
